# Generated by Django 4.0.5 on 2022-06-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inventory_quantity', models.IntegerField()),
                ('web_pic', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
